# -*- coding: utf-8 -*-
"""Single layer perceptron

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NSbCzlYv_NU2Lx0R3Mj1R0Ynvac4NIak
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam


x=np.array([[2,8],
           [3,7],
           [4,6],
           [5,5],
           [6,4],
           [1,10],
           [7,3],
           [8,2],
           [2,9],
           [9,1]])
y=np.array([[0],
   [0],
   [1],
   [1],
   [1],
   [0],
   [1],
   [1],
   [0],
   [1]])


model=Sequential([Dense(1,input_dim=2,activation='sigmoid')])
model.compile(optimizer=Adam(learning_rate=0.1),loss='binary_crossentropy',metrics=['accuracy'])


model.fit(x,y,epochs=100,verbose=0)


for i in x:
  prediction=model.predict(np.array([i]))
  print(f"input:- {i} predictio:- {round(prediction.flatten()[0])}")